function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // init_game
	global.__objectDepths[1] = 0; // init_intro
	global.__objectDepths[2] = -10000001; // obj_view
	global.__objectDepths[3] = 0; // obj_mplayer
	global.__objectDepths[4] = 0; // obj_mplayer_mini
	global.__objectDepths[5] = 0; // obj_lplayer
	global.__objectDepths[6] = 0; // obj_lplayer_2
	global.__objectDepths[7] = 0; // obj_lplayer_dunk
	global.__objectDepths[8] = 0; // obj_mplayer_2
	global.__objectDepths[9] = 0; // obj_fire
	global.__objectDepths[10] = 0; // obj_thunder
	global.__objectDepths[11] = 0; // par_player
	global.__objectDepths[12] = 0; // obj_mplayer_stunned
	global.__objectDepths[13] = 0; // obj_lplayer_stunned
	global.__objectDepths[14] = 0; // obj_lplayer_change
	global.__objectDepths[15] = 0; // obj_goomba
	global.__objectDepths[16] = 0; // obj_shyguy
	global.__objectDepths[17] = 0; // par_enemy
	global.__objectDepths[18] = 0; // obj_enemy_stunned
	global.__objectDepths[19] = 0; // obj_rock
	global.__objectDepths[20] = -9999; // obj_electric
	global.__objectDepths[21] = -9999; // obj_torch
	global.__objectDepths[22] = -10000; // obj_qblock
	global.__objectDepths[23] = 0; // obj_beanspot
	global.__objectDepths[24] = -10000; // obj_gate
	global.__objectDepths[25] = 0; // obj_grassland_tree
	global.__objectDepths[26] = -10000; // obj_z16
	global.__objectDepths[27] = -10000; // obj_z32
	global.__objectDepths[28] = -10000; // obj_z48
	global.__objectDepths[29] = -10000; // obj_z64
	global.__objectDepths[30] = -10000; // obj_z80
	global.__objectDepths[31] = -10000; // obj_z96
	global.__objectDepths[32] = -10000; // obj_z112
	global.__objectDepths[33] = -10000; // obj_z128
	global.__objectDepths[34] = -10000; // obj_z144
	global.__objectDepths[35] = -10000; // obj_z160
	global.__objectDepths[36] = -10000; // obj_z176
	global.__objectDepths[37] = -10000; // obj_z192
	global.__objectDepths[38] = -10000; // obj_z208
	global.__objectDepths[39] = -10000; // obj_z224
	global.__objectDepths[40] = -10000; // obj_z240
	global.__objectDepths[41] = -10000; // obj_z256
	global.__objectDepths[42] = 0; // obj_zmask
	global.__objectDepths[43] = 0; // obj_zslope
	global.__objectDepths[44] = -10000; // obj_h16
	global.__objectDepths[45] = -10000; // obj_h32
	global.__objectDepths[46] = -10000; // obj_h48
	global.__objectDepths[47] = -10000; // obj_h64
	global.__objectDepths[48] = -10000; // obj_h80
	global.__objectDepths[49] = -10000; // obj_h96
	global.__objectDepths[50] = -10000; // obj_h112
	global.__objectDepths[51] = -10000; // obj_h128
	global.__objectDepths[52] = -10000; // obj_h144
	global.__objectDepths[53] = -10000; // obj_h160
	global.__objectDepths[54] = -10000; // obj_h176
	global.__objectDepths[55] = -10000; // obj_h192
	global.__objectDepths[56] = -10000; // obj_h208
	global.__objectDepths[57] = -10000; // obj_h224
	global.__objectDepths[58] = -10000; // obj_h240
	global.__objectDepths[59] = -10000; // obj_h256
	global.__objectDepths[60] = -10000; // obj_solid
	global.__objectDepths[61] = -10000; // obj_dunk_solid
	global.__objectDepths[62] = -10000; // obj_mini_solid
	global.__objectDepths[63] = -10000; // obj_metal_solid
	global.__objectDepths[64] = -10000; // obj_warp
	global.__objectDepths[65] = -10000; // obj_dark
	global.__objectDepths[66] = -10000; // obj_light
	global.__objectDepths[67] = 12; // obj_lava
	global.__objectDepths[68] = 12; // obj_lavafall
	global.__objectDepths[69] = 12; // obj_water
	global.__objectDepths[70] = 0; // obj_waterfall
	global.__objectDepths[71] = 0; // obj_mariob
	global.__objectDepths[72] = 0; // obj_luigib
	global.__objectDepths[73] = 0; // obj_goombab
	global.__objectDepths[74] = 0; // obj_popb
	global.__objectDepths[75] = 0; // obj_mossyb
	global.__objectDepths[76] = 0; // obj_lakitub
	global.__objectDepths[77] = 0; // obj_lakituball
	global.__objectDepths[78] = 0; // obj_spinyb
	global.__objectDepths[79] = 0; // obj_shyguyb
	global.__objectDepths[80] = 0; // obj_shyguyrock
	global.__objectDepths[81] = 0; // obj_autobombb
	global.__objectDepths[82] = 0; // obj_bowserb
	global.__objectDepths[83] = 0; // par_enemyground
	global.__objectDepths[84] = 0; // par_enemyspikedground
	global.__objectDepths[85] = 0; // par_enemysky
	global.__objectDepths[86] = 0; // par_enemyspikedsky
	global.__objectDepths[87] = 0; // obj_enemyallb
	global.__objectDepths[88] = 0; // obj_enemyallspikedb
	global.__objectDepths[89] = 0; // obj_brosattack
	global.__objectDepths[90] = 0; // obj_levelupbonus
	global.__objectDepths[91] = 0; // obj_battlecontrol
	global.__objectDepths[92] = -100000000; // obj_battlestart
	global.__objectDepths[93] = 0; // obj_fireballm
	global.__objectDepths[94] = 0; // obj_fireballl
	global.__objectDepths[95] = 0; // obj_fireballprojectile
	global.__objectDepths[96] = 0; // obj_itemb
	global.__objectDepths[97] = 0; // obj_jumpblock
	global.__objectDepths[98] = 0; // obj_brosblock
	global.__objectDepths[99] = 0; // obj_runblock
	global.__objectDepths[100] = 0; // obj_itemblock
	global.__objectDepths[101] = 0; // obj_rankbattle
	global.__objectDepths[102] = 0; // obj_pointsbattle
	global.__objectDepths[103] = 0; // obj_healpointsbattle
	global.__objectDepths[104] = 0; // obj_totaldamage
	global.__objectDepths[105] = 0; // obj_mplayer_electrocute
	global.__objectDepths[106] = 0; // obj_treebase
	global.__objectDepths[107] = 0; // obj_spin
	global.__objectDepths[108] = 0; // obj_spin_alarm
	global.__objectDepths[109] = 0; // obj_blockshadow
	global.__objectDepths[110] = -100000; // obj_coin
	global.__objectDepths[111] = 0; // obj_gotoprev
	global.__objectDepths[112] = 0; // obj_prevroom
	global.__objectDepths[113] = 0; // obj_title
	global.__objectDepths[114] = 0; // obj_fileselect
	global.__objectDepths[115] = 0; // obj_credits
	global.__objectDepths[116] = 0; // obj_creditstext
	global.__objectDepths[117] = 1; // obj_creditsimages
	global.__objectDepths[118] = -99; // obj_fadein
	global.__objectDepths[119] = -99; // obj_fadeout
	global.__objectDepths[120] = 0; // obj_battleselectbeta_nx
	global.__objectDepths[121] = 0; // obj_player_dummy
	global.__objectDepths[122] = 0; // obj_overworld_dummy
	global.__objectDepths[123] = 0; // obj_item_dummy
	global.__objectDepths[124] = -1000; // obj_audio_loop_sound
	global.__objectDepths[125] = 0; // obj_otheraudio
	global.__objectDepths[126] = -999999; // obj_debugger
	global.__objectDepths[127] = 0; // readme


	global.__objectNames[0] = "init_game";
	global.__objectNames[1] = "init_intro";
	global.__objectNames[2] = "obj_view";
	global.__objectNames[3] = "obj_mplayer";
	global.__objectNames[4] = "obj_mplayer_mini";
	global.__objectNames[5] = "obj_lplayer";
	global.__objectNames[6] = "obj_lplayer_2";
	global.__objectNames[7] = "obj_lplayer_dunk";
	global.__objectNames[8] = "obj_mplayer_2";
	global.__objectNames[9] = "obj_fire";
	global.__objectNames[10] = "obj_thunder";
	global.__objectNames[11] = "par_player";
	global.__objectNames[12] = "obj_mplayer_stunned";
	global.__objectNames[13] = "obj_lplayer_stunned";
	global.__objectNames[14] = "obj_lplayer_change";
	global.__objectNames[15] = "obj_goomba";
	global.__objectNames[16] = "obj_shyguy";
	global.__objectNames[17] = "par_enemy";
	global.__objectNames[18] = "obj_enemy_stunned";
	global.__objectNames[19] = "obj_rock";
	global.__objectNames[20] = "obj_electric";
	global.__objectNames[21] = "obj_torch";
	global.__objectNames[22] = "obj_qblock";
	global.__objectNames[23] = "obj_beanspot";
	global.__objectNames[24] = "obj_gate";
	global.__objectNames[25] = "obj_grassland_tree";
	global.__objectNames[26] = "obj_z16";
	global.__objectNames[27] = "obj_z32";
	global.__objectNames[28] = "obj_z48";
	global.__objectNames[29] = "obj_z64";
	global.__objectNames[30] = "obj_z80";
	global.__objectNames[31] = "obj_z96";
	global.__objectNames[32] = "obj_z112";
	global.__objectNames[33] = "obj_z128";
	global.__objectNames[34] = "obj_z144";
	global.__objectNames[35] = "obj_z160";
	global.__objectNames[36] = "obj_z176";
	global.__objectNames[37] = "obj_z192";
	global.__objectNames[38] = "obj_z208";
	global.__objectNames[39] = "obj_z224";
	global.__objectNames[40] = "obj_z240";
	global.__objectNames[41] = "obj_z256";
	global.__objectNames[42] = "obj_zmask";
	global.__objectNames[43] = "obj_zslope";
	global.__objectNames[44] = "obj_h16";
	global.__objectNames[45] = "obj_h32";
	global.__objectNames[46] = "obj_h48";
	global.__objectNames[47] = "obj_h64";
	global.__objectNames[48] = "obj_h80";
	global.__objectNames[49] = "obj_h96";
	global.__objectNames[50] = "obj_h112";
	global.__objectNames[51] = "obj_h128";
	global.__objectNames[52] = "obj_h144";
	global.__objectNames[53] = "obj_h160";
	global.__objectNames[54] = "obj_h176";
	global.__objectNames[55] = "obj_h192";
	global.__objectNames[56] = "obj_h208";
	global.__objectNames[57] = "obj_h224";
	global.__objectNames[58] = "obj_h240";
	global.__objectNames[59] = "obj_h256";
	global.__objectNames[60] = "obj_solid";
	global.__objectNames[61] = "obj_dunk_solid";
	global.__objectNames[62] = "obj_mini_solid";
	global.__objectNames[63] = "obj_metal_solid";
	global.__objectNames[64] = "obj_warp";
	global.__objectNames[65] = "obj_dark";
	global.__objectNames[66] = "obj_light";
	global.__objectNames[67] = "obj_lava";
	global.__objectNames[68] = "obj_lavafall";
	global.__objectNames[69] = "obj_water";
	global.__objectNames[70] = "obj_waterfall";
	global.__objectNames[71] = "obj_mariob";
	global.__objectNames[72] = "obj_luigib";
	global.__objectNames[73] = "obj_goombab";
	global.__objectNames[74] = "obj_popb";
	global.__objectNames[75] = "obj_mossyb";
	global.__objectNames[76] = "obj_lakitub";
	global.__objectNames[77] = "obj_lakituball";
	global.__objectNames[78] = "obj_spinyb";
	global.__objectNames[79] = "obj_shyguyb";
	global.__objectNames[80] = "obj_shyguyrock";
	global.__objectNames[81] = "obj_autobombb";
	global.__objectNames[82] = "obj_bowserb";
	global.__objectNames[83] = "par_enemyground";
	global.__objectNames[84] = "par_enemyspikedground";
	global.__objectNames[85] = "par_enemysky";
	global.__objectNames[86] = "par_enemyspikedsky";
	global.__objectNames[87] = "obj_enemyallb";
	global.__objectNames[88] = "obj_enemyallspikedb";
	global.__objectNames[89] = "obj_brosattack";
	global.__objectNames[90] = "obj_levelupbonus";
	global.__objectNames[91] = "obj_battlecontrol";
	global.__objectNames[92] = "obj_battlestart";
	global.__objectNames[93] = "obj_fireballm";
	global.__objectNames[94] = "obj_fireballl";
	global.__objectNames[95] = "obj_fireballprojectile";
	global.__objectNames[96] = "obj_itemb";
	global.__objectNames[97] = "obj_jumpblock";
	global.__objectNames[98] = "obj_brosblock";
	global.__objectNames[99] = "obj_runblock";
	global.__objectNames[100] = "obj_itemblock";
	global.__objectNames[101] = "obj_rankbattle";
	global.__objectNames[102] = "obj_pointsbattle";
	global.__objectNames[103] = "obj_healpointsbattle";
	global.__objectNames[104] = "obj_totaldamage";
	global.__objectNames[105] = "obj_mplayer_electrocute";
	global.__objectNames[106] = "obj_treebase";
	global.__objectNames[107] = "obj_spin";
	global.__objectNames[108] = "obj_spin_alarm";
	global.__objectNames[109] = "obj_blockshadow";
	global.__objectNames[110] = "obj_coin";
	global.__objectNames[111] = "obj_gotoprev";
	global.__objectNames[112] = "obj_prevroom";
	global.__objectNames[113] = "obj_title";
	global.__objectNames[114] = "obj_fileselect";
	global.__objectNames[115] = "obj_credits";
	global.__objectNames[116] = "obj_creditstext";
	global.__objectNames[117] = "obj_creditsimages";
	global.__objectNames[118] = "obj_fadein";
	global.__objectNames[119] = "obj_fadeout";
	global.__objectNames[120] = "obj_battleselectbeta_nx";
	global.__objectNames[121] = "obj_player_dummy";
	global.__objectNames[122] = "obj_overworld_dummy";
	global.__objectNames[123] = "obj_item_dummy";
	global.__objectNames[124] = "obj_audio_loop_sound";
	global.__objectNames[125] = "obj_otheraudio";
	global.__objectNames[126] = "obj_debugger";
	global.__objectNames[127] = "readme";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
